# Continuous Integration workflow for mobile-depth-map
# Pushes and PRs on main run lint, typecheck, build, then post to Discord on success.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ─── Checkout repo ────────────────────────────────────────────────
      - uses: actions/checkout@v4

      # ─── Setup Node (18.x) ────────────────────────────────────────────
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ─── Install pnpm & restore cache ────────────────────────────────
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # ─── Install dependencies ───────────────────────────────────────── ─────────────────────────────────────────
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --no-frozen-lockfile

      # ─── Lint & type-check the monorepo ───────────────────────────────
      - name: Lint & Type-check
        run: pnpm dlx turbo run lint typecheck --concurrency=50%

      # ─── Build all packages ───────────────────────────────────────────
      - name: Build
        run: pnpm dlx turbo run build --concurrency=50%

            # ─── Discord notification (only on success) ───────────────────────
      - name: Notify Discord
        if: success()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            ✅ **${{ github.repository }}** commit `${{ github.sha }}` built & lint-checked successfully.
